baseURL = 'https://v3rtigo.org'
languageCode = 'en-us'
title = 'Adventures in IoT'
theme = 'terminal'
[params]
	Logo.logoText = "Adventures in IoT"
# ["orange", "blue", "red", "green", "pink"]
    themeColor = "green"
# set theme to full screen width
    fullWidthTheme = false

# center theme with default width
    centerTheme = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Adventures in IoT"
    owner = "v3rtigo"
    keywords = ""
    copyright = "v3rtigo"
    menuMore = "Show more"
    readMore = ""
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Bruh..."
    missingBackButtonLabel = "Why are you here?"
    words = "words"


# show selector to switch language - NOT WORKING
    showLanguageSelector = true