title = 'Adventures in IoT'
theme = 'terminal'
baseURL = 'https://v3rtigo.org'
copyright = "© v3rtigo 2024"

[languages]
  [languages.en]
    [languages.en.params]
    baseURL = 'https://v3rtigo.org'
    languageCode = 'en-us'
    title = "Adventures in IoT"
    owner = "v3rtigo"
    keywords = ""
    menuMore = "Show more"
    readMore = ""
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Bruh..."
    missingBackButtonLabel = "Why are you here?"
    centerTheme = true
    Logo.logoText = "Adventures in IoT"
# ["orange", "blue", "red", "green", "pink"]
    themeColor = "green"
# set theme to full screen width
    fullWidthTheme = false
# if you set this to 0, only submenu trigger will be visible
    showMenuItems = 4

  [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "Hacking Trash"
      name = "Hacking Trash"
      url = "/hacking-trash"    
    [[languages.en.menu.main]]
      identifier = "Resources"
      name = "Resources"
      url = "/resources"
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"
    [[languages.en.menu.main]]
      identifier = "News"
      name = "News"
      url = "/news"





# show selector to switch language - NO OTHER LANGUAGES SETUP YET
    showLanguageSelector = true